python-oslo.config: add RDEPENDS on python-importlib-metadata
python-importlib-metadata is required by python-oslo.config_git
or it fails with:

Traceback (most recent call last):
  File "/usr/bin/oslo-config-generator", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/oslo_config/generator.py", line 770, in main
    generate(conf)
  File "/usr/lib/python2.7/site-packages/kombu/utils/compat.py", line 14, in <module>
    import importlib_metadata
ImportError: No module named importlib_metadata

fix #211

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>