python-kombu: add RDEPENDS on python-importlib-metadata
python-kombu requires python-importlib-metadata or it fails with:

  File "/usr/lib/python2.7/site-packages/kombu/utils/compat.py", line
  14, in <module>
      import importlib_metadata
  ImportError: No module named importlib_metadata

fix #228

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>