openvswitch: add RDEPENDS on hwdata
Add the missing dependency on hwdata or it fails with:

controller-0:~# /usr/share/openvswitch/scripts/dpdk-pmdinfo.py
Traceback (most recent call last):
  File "/usr/share/openvswitch/scripts/dpdk-pmdinfo.py", line 612, in <module>
    main()
  File "/usr/share/openvswitch/scripts/dpdk-pmdinfo.py", line 568, in main
    pcidb = PCIIds(options.pcifile)
  File "/usr/share/openvswitch/scripts/dpdk-pmdinfo.py", line 154, in __init__
    self.readLocal(filename)
  File "/usr/share/openvswitch/scripts/dpdk-pmdinfo.py", line 216, in readLocal
    self.contents = open(filename).readlines()
IOError: [Errno 2] No such file or directory: '/usr/share/hwdata/pci.ids'

fix #286

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>